import:
  - java_base.yml
  - java_linux_arm64.yml
  - java_windows_amd64.yml

env:
  global:
    - DEPLOY_OS=linux
    - DEPLOY_JDK=openjdk11
    - DEPLOY_REPO=nbbrd/sandbox
    - DEPLOY_BIN=target/binaries/*

services:
  - xvfb

jobs:
  include:
    - name: "linux-amd64-openjdk8"
      jdk: openjdk8
      os: linux
      
    - name: "linux-amd64-openjdk11"
      jdk: openjdk11
      os: linux
      
    - name: "linux-amd64-openjdk-ea"
      jdk: openjdk-ea
      os: linux

    - name: "linux-arm64-openjdk11"
      jdk: openjdk11
      <<: *_java_linux_arm64
    
    - name: "macos-amd64-openjdk11"
      jdk: openjdk11
      os: osx
      
    - name: "windows-amd64-openjdk11"
      env: TRAVIS_JDK_VERSION=openjdk11
      <<: *_java_windows_amd64
      
  allow_failures:
    - jdk: openjdk-ea
    
deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Maven releases from tags
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

cache:
  directories:
    - $HOME/.m2
