import:
  - java_base.yml
  - java_linux_arm64.yml
  - java_windows_amd64.yml
  - maven_snapshots_from_develop.yml
  - maven_releases_from_tags.yml
  - github_releases_from_tags.yml

env:
  global:
    - DEPLOY_OS=linux
    - DEPLOY_JDK=openjdk11
    - DEPLOY_REPO=nbbrd/sandbox
    - DEPLOY_BIN=target/binaries/*

services:
  - xvfb

jobs:
  include:
    - name: "linux-amd64-openjdk8"
      jdk: openjdk8
      os: linux
      
    - name: "linux-amd64-openjdk11"
      jdk: openjdk11
      os: linux
      
    - name: "linux-amd64-openjdk-ea"
      jdk: openjdk-ea
      os: linux

    - name: "linux-arm64-openjdk11"
      jdk: openjdk11
      <<: *_java_linux_arm64
    
    - name: "macos-amd64-openjdk11"
      jdk: openjdk11
      os: osx
      
    - name: "windows-amd64-openjdk11"
      env: TRAVIS_JDK_VERSION=openjdk11
      <<: *_java_windows_amd64
      
  allow_failures:
    - jdk: openjdk-ea
    
cache:
  directories:
    - $HOME/.m2
