dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea

jobs:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - jdk: openjdk-ea

env:
  global:
    - DEPLOY_OS=linux
    - DEPLOY_JDK=openjdk11
    - DEPLOY_REPO=nbbrd/sandbox
    - DEPLOY_BIN=target/binaries/*
    
deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Maven releases from tags
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

cache:
  directories:
    - $HOME/.m2
