language: java
jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - DEPLOY_JDK=oraclejdk8
    - DEPLOY_REPO=nbbrd/sandbox

before_install:
  - shopt -s expand_aliases
  - alias mvn_deploy='echo hello'

deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn_deploy
    skip_cleanup: true
    on:
      branch: develop
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

  # Maven releases from master branch
  - provider: script
    script: mvn_deploy
    skip_cleanup: true
    on:
      branch: master
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK
