language: java
jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - DEPLOY_JDK=oraclejdk8
    - DEPLOY_REPO=nbbrd/sandbox

deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: echo hello snapshot
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

  # Maven releases from master branch
  - provider: script
    script: echo hello release
    skip_cleanup: true
    on:
      branch: master
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

  # Github releases from master branch & tag
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    file_glob: true
    file: "target/*bin.jar"
    on:
      branch: master
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK
