language: java
jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - DEPLOY_JDK=oraclejdk8
    - DEPLOY_REPO=nbbrd/sandbox

deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: echo hello snapshots
    skip_cleanup: true
    on:
      branch: develop
      repo: $DEPLOY_REPO
      jdk: $DEPLOY_JDK
      condition: $TRAVIS_PULL_REQUEST = "false"

  # Maven releases from master branch
  - provider: script
    script: echo hello releases
    skip_cleanup: true
    on:
      branch: master
      repo: $DEPLOY_REPO
      jdk: $DEPLOY_JDK
      condition: $TRAVIS_PULL_REQUEST = "false"
