dist: xenial
language: java

jobs:
  include:
    - stage: Test
      name: "Linux + OpenJDK8"
      os: linux
      jdk: openjdk8
      
    - stage: Test
      name: "Linux + OpenJDK11"
      os: linux
      jdk: openjdk11
      
    - stage: Test
      name: "Linux + OpenJDK-EA"
      os: linux
      jdk: openjdk-ea
      
    - stage: Test
      name: "macOS + OpenJDK11"
      os: osx
      jdk: openjdk11
      
    - stage: Test
      name: "Windows + OpenJDK11"
      os: windows
      language: shell
      install:
        - choco install openjdk11
        - choco install maven
        - cmd.exe //c "RefreshEnv.cmd"
        - eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
      script:
        - java -Xmx32m -version
        - javac -J-Xmx32m -version
        - echo $PATH
        - echo $M2_HOME
        - echo %M2_HOME%
        - mvn.bat install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - mvn.bat test -B
        
  allow_failures:
    - jdk: openjdk-ea

env:
  global:
    - DEPLOY_OS=linux
    - DEPLOY_JDK=openjdk11
    - DEPLOY_REPO=nbbrd/sandbox
    - DEPLOY_BIN=target/binaries/*
    
deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Maven releases from tags
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

cache:
  directories:
    - $HOME/.m2
