language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

# some comments
deploy:
  - provider: script
    script: echo hello world
    skip_cleanup: true
    on:
      repo: nbbrd/sandbox
      branch: master
      jdk: oraclejdk8
      condition: $TRAVIS_PULL_REQUEST = "false"
