language: java
jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

deploy:
 # Maven snapshots from develop & jdk8
 - provider: script
    script: echo hello snapshots
    skip_cleanup: true
    on:
      repo: nbbrd/sandbox
      branch: develop
      jdk: oraclejdk8
      condition: $TRAVIS_PULL_REQUEST = "false"

 # Maven releases from master & jdk8
 - provider: script
    script: echo hello releases
    skip_cleanup: true
    on:
      repo: nbbrd/sandbox
      branch: master
      jdk: oraclejdk8
      condition: $TRAVIS_PULL_REQUEST = "false"
