language: java
jdk:
  - oraclejdk8
  - openjdk11

env:
  global:
    - DEPLOY_JDK=oraclejdk8
    - DEPLOY_REPO=nbbrd/sandbox
    - DEPLOY_BIN=target/*bin.jar
    
before_script:
  - shopt -s expand_aliases
  - alias mvn_project_version='mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout'
  - mvn_project_version

deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

  # Maven releases from tags
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

cache:
  directories:
    - $HOME/.m2
